#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page.

# update
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i 's|# server_name _;|server_name _;|' /etc/nginx/sites-enabled/default
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.github.com/blessedb1/;\n\t}\n' /etc/nginx/sites-enabled/default
sudo nginx -t

service nginx restart
