#!/usr/bin/env bash
# setting up custom headers

sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

#  create the index page
echo 'Hello World!' | sudo tee  /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html



new_string="server_name_;\n\tadd_header X-Served-By \$hostname;\n"

sudo sed -i "server_name_;/$new_string/"  /etc/nginx/sites-enabled/default


# code to configure redirect for 404 error page
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart

