#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  garbau-frontend
        bind *:80
        mode http
        default_backend garbau-backend
backend garbau-backend
        balance roundrobin
        server 169701-web-01 34.201.68.164:80 check
        server 169701-web-02 54.157.165.159:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
